### ISSUE TITLE
UnicodeDecodeError when training

### ISSUE THREAD

**Issue by zjxi** [gidariss/FewShotWithoutForgetting#20]

**Comment by EternalWang** [comment]
> When I run the 1st training stage :
> 
> ```
> CUDA_VISIBLE_DEVICES=0 python train.py --config=miniImageNet_Conv128CosineClassifier
> ```
> 
> But it comes to an error like this :
> 
> ```
> Traceback (most recent call last):
>   File "train.py", line 72, in <module>
>     dataset_train = MiniImageNet(phase=train_split)
>   File "C:\Users\lenovo\Desktop\FewShotWithoutForgetting\dataloader.py", line 122, in __init__
>     data_train = load_data(file_train_categories_train_phase)
>   File "C:\Users\lenovo\Desktop\FewShotWithoutForgetting\dataloader.py", line 90, in load_data
>     data = pickle.load(fo)
> UnicodeDecodeError: 'ascii' codec can't decode byte 0x91 in position 1: ordinal not in range(128)
> ```
> 
> Environment `Python 3.7, pytorch 0.4`
> Thanks.

Hello, have you fixed this problem?

**Comment by ElecRex** [comment]
> > When I run the 1st training stage :
> > ```
> > CUDA_VISIBLE_DEVICES=0 python train.py --config=miniImageNet_Conv128CosineClassifier
> > ```
> > 
> > 
> > But it comes to an error like this :
> > ```
> > Traceback (most recent call last):
> >   File "train.py", line 72, in <module>
> >     dataset_train = MiniImageNet(phase=train_split)
> >   File "C:\Users\lenovo\Desktop\FewShotWithoutForgetting\dataloader.py", line 122, in __init__
> >     data_train = load_data(file_train_categories_train_phase)
> >   File "C:\Users\lenovo\Desktop\FewShotWithoutForgetting\dataloader.py", line 90, in load_data
> >     data = pickle.load(fo)
> > UnicodeDecodeError: 'ascii' codec can't decode byte 0x91 in position 1: ordinal not in range(128)
> > ```
> > 
> > 
> > Environment `Python 3.7, pytorch 0.4`
> > Thanks.
> 
> Hello, have you fixed this problem?

This problem had been fixed : ```data = pickle.load(fo, encoding='bytes')```, 
but I got other problems

**Comment by EternalWang** [comment]
Thanks a lot! 
Maybe we can work on it together.

**Comment by EternalWang** [comment]
However, when using the ‘bytes’ encoding rule, I met another problem below:
```
Traceback (most recent call last):
  File "train.py", line 72, in <module>
    dataset_train = MiniImageNet(phase=train_split)
  File "/media/eternal-wang/D/Research/FSL/FewShotWithoutForgetting-master/dataloader.py", line 124, in __init__
    self.data = data_train['data']
KeyError: 'data'

```
But after changed into ‘iso-8859-1’，the problem disappeared.

**Comment by ElecRex** [comment]
> However, when using the ‘bytes’ encoding rule, I met another problem below:
> 
> ```
> Traceback (most recent call last):
>   File "train.py", line 72, in <module>
>     dataset_train = MiniImageNet(phase=train_split)
>   File "/media/eternal-wang/D/Research/FSL/FewShotWithoutForgetting-master/dataloader.py", line 124, in __init__
>     self.data = data_train['data']
> KeyError: 'data'
> ```
> 
> But after changed into ‘iso-8859-1’，the problem disappeared.

Changing ```bytes``` to ```iso-8859-1``` ?

**Comment by EternalWang** [comment]
Yes.
By the way, I finally make the code running after fixed several bugs.

**Comment by ElecRex** [comment]
I got the error in  the log after Changing 'bytes' to 'iso-8859-1' :
```
Traceback (most recent call last):
  File "/content/drive/My Drive/app/fewshotwithoutforgetting/train.py", line 100, in <module>
    algorithm = alg.FewShot(config)
  File "/content/drive/My Drive/app/fewshotwithoutforgetting/algorithms/FewShot.py", line 32, in __init__
    Algorithm.__init__(self, opt)
  File "/content/drive/My Drive/app/fewshotwithoutforgetting/algorithms/Algorithm.py", line 28, in __init__
    self.init_all_networks()
  File "/content/drive/My Drive/app/fewshotwithoutforgetting/algorithms/Algorithm.py", line 84, in init_all_networks
    def_file, net_opt, pretrained_path, key)
  File "/content/drive/My Drive/app/fewshotwithoutforgetting/algorithms/Algorithm.py", line 90, in init_network
    raise ValueError('Non existing file: {0}'.format(net_def_file))
ValueError: Non existing file: architectures/ConvNet.py
```
I can't figure it out where is the correct path of this file.
Thanks. @EternalWang

**Comment by EternalWang** [comment]
I haven't met this error.
Maybe you should check the path of **./architectures/ConvNet.py** ？

**Comment by ElecRex** [comment]
Have you met this issue before? @EternalWang 
```
Traceback (most recent call last):
  File "/content/drive/My Drive/app/fewshotwithoutforgetting/train.py", line 110, in <module>
    algorithm.solve(dloader_train, dloader_test)
  File "/content/drive/My Drive/app/fewshotwithoutforgetting/algorithms/Algorithm.py", line 278, in solve
    train_stats = self.run_train_epoch(data_loader_train, self.curr_epoch)
  File "/content/drive/My Drive/app/fewshotwithoutforgetting/algorithms/Algorithm.py", line 308, in run_train_epoch
    self.global_iter = self.curr_epoch * len(data_loader) + self.biter
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by EternalWang** [comment]
change 

> self.global_iter = self.curr_epoch * len(data_loader) + self.biter

 to

>  self.global_iter = self.curr_epoch * len(data_loader()) + self.biter

**Comment by ElecRex** [comment]
Sorry, how to deal with this problem? @EternalWang 
```
Traceback (most recent call last):
  File "/content/drive/My Drive/app/fewshotwithoutforgetting/train.py", line 110, in <module>
    algorithm.solve(dloader_train, dloader_test)
  File "/content/drive/My Drive/app/fewshotwithoutforgetting/algorithms/Algorithm.py", line 286, in solve
    eval_stats = self.evaluate(data_loader_test)
  File "/content/drive/My Drive/app/fewshotwithoutforgetting/algorithms/Algorithm.py", line 330, in evaluate
    for idx, batch in enumerate(tqdm(dloader())):
  File "/usr/local/lib/python3.6/dist-packages/tqdm/_tqdm.py", line 1022, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 560, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 560, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/usr/local/lib/python3.6/dist-packages/torchnet/dataset/listdataset.py", line 54, in __getitem__
    return self.load(self.list[idx])
  File "/content/drive/My Drive/app/fewshotwithoutforgetting/dataloader.py", line 445, in load_function
    Exemplars, Test, Kall, nKbase = self.sample_episode()
  File "/content/drive/My Drive/app/fewshotwithoutforgetting/dataloader.py", line 407, in sample_episode
    Knovel, nTestNovel, nExemplars, nKbase)
  File "/content/drive/My Drive/app/fewshotwithoutforgetting/dataloader.py", line 383, in sample_train_and_test_examples_for_novel_categories
    sample_size=(nEvalExamplesPerClass + nExemplars))
  File "/content/drive/My Drive/app/fewshotwithoutforgetting/dataloader.py", line 250, in sampleImageIdsFrom
    return random.sample(self.dataset.label2ind[cat_id], sample_size)
  File "/usr/lib/python3.6/random.py", line 321, in sample
    result = [None] * k
TypeError: can't multiply sequence by non-int of type 'float'
```

**Comment by EternalWang** [comment]
change 
> nEvalExamplesPerClass = nTestNovel / nKnovel

to

> nEvalExamplesPerClass = int(nTestNovel / nKnovel)

in dataloader.py at line 380

**Comment by ElecRex** [comment]
@EternalWang 
```
Traceback (most recent call last):
  File "/content/drive/My Drive/app/fewshotwithoutforgetting/train.py", line 110, in <module>
    algorithm.solve(dloader_train, dloader_test)
  File "/content/drive/My Drive/app/fewshotwithoutforgetting/algorithms/Algorithm.py", line 286, in solve
    eval_stats = self.evaluate(data_loader_test)
  File "/content/drive/My Drive/app/fewshotwithoutforgetting/algorithms/Algorithm.py", line 332, in evaluate
    eval_stats_this = self.evaluation_step(batch)
  File "/content/drive/My Drive/app/fewshotwithoutforgetting/algorithms/FewShot.py", line 84, in evaluation_step
    return self.process_batch(batch, do_train=False)
  File "/content/drive/My Drive/app/fewshotwithoutforgetting/algorithms/FewShot.py", line 87, in process_batch
    process_type = self.set_tensors(batch)
  File "/content/drive/My Drive/app/fewshotwithoutforgetting/algorithms/FewShot.py", line 55, in set_tensors
    self.nKbase = nKbase.squeeze()[0]
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number
```
How to fix this problem？Thanks

**Comment by EternalWang** [comment]
你已经是个成熟的程序员了，应该学会开动小脑瓜自己debug了。
